/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = pricelist.Client.OpenAPIDateConverter;

namespace pricelist.Model
{
    /// <summary>
    /// PricelistGetPriceListItem
    /// </summary>
    [DataContract(Name = "pricelistGetPriceListItem")]
    public partial class PricelistGetPriceListItem : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public PricelistCurrency? Currency { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PricelistGetPriceListItem" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="grn">grn.</param>
        /// <param name="itemGrn">itemGrn.</param>
        /// <param name="price">price.</param>
        /// <param name="doubleFormatPrice">doubleFormatPrice.</param>
        /// <param name="endDatePrice">endDatePrice.</param>
        /// <param name="basePrice">basePrice.</param>
        /// <param name="doubleFormatBasePrice">doubleFormatBasePrice.</param>
        /// <param name="currency">currency.</param>
        /// <param name="hasTierPrices">hasTierPrices.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        public PricelistGetPriceListItem(string id = default(string), string grn = default(string), string itemGrn = default(string), PricelistMoney price = default(PricelistMoney), double doubleFormatPrice = default(double), DateTime endDatePrice = default(DateTime), PricelistMoney basePrice = default(PricelistMoney), double doubleFormatBasePrice = default(double), PricelistCurrency? currency = default(PricelistCurrency?), bool hasTierPrices = default(bool), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime))
        {
            this.Id = id;
            this.Grn = grn;
            this.ItemGrn = itemGrn;
            this.Price = price;
            this.DoubleFormatPrice = doubleFormatPrice;
            this.EndDatePrice = endDatePrice;
            this.BasePrice = basePrice;
            this.DoubleFormatBasePrice = doubleFormatBasePrice;
            this.Currency = currency;
            this.HasTierPrices = hasTierPrices;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Grn
        /// </summary>
        [DataMember(Name = "grn", EmitDefaultValue = false)]
        public string Grn { get; set; }

        /// <summary>
        /// Gets or Sets ItemGrn
        /// </summary>
        [DataMember(Name = "itemGrn", EmitDefaultValue = false)]
        public string ItemGrn { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name = "price", EmitDefaultValue = false)]
        public PricelistMoney Price { get; set; }

        /// <summary>
        /// Gets or Sets DoubleFormatPrice
        /// </summary>
        [DataMember(Name = "doubleFormatPrice", EmitDefaultValue = false)]
        public double DoubleFormatPrice { get; set; }

        /// <summary>
        /// Gets or Sets EndDatePrice
        /// </summary>
        [DataMember(Name = "endDatePrice", EmitDefaultValue = false)]
        public DateTime EndDatePrice { get; set; }

        /// <summary>
        /// Gets or Sets BasePrice
        /// </summary>
        [DataMember(Name = "basePrice", EmitDefaultValue = false)]
        public PricelistMoney BasePrice { get; set; }

        /// <summary>
        /// Gets or Sets DoubleFormatBasePrice
        /// </summary>
        [DataMember(Name = "doubleFormatBasePrice", EmitDefaultValue = false)]
        public double DoubleFormatBasePrice { get; set; }

        /// <summary>
        /// Gets or Sets HasTierPrices
        /// </summary>
        [DataMember(Name = "hasTierPrices", EmitDefaultValue = true)]
        public bool HasTierPrices { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PricelistGetPriceListItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Grn: ").Append(Grn).Append("\n");
            sb.Append("  ItemGrn: ").Append(ItemGrn).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  DoubleFormatPrice: ").Append(DoubleFormatPrice).Append("\n");
            sb.Append("  EndDatePrice: ").Append(EndDatePrice).Append("\n");
            sb.Append("  BasePrice: ").Append(BasePrice).Append("\n");
            sb.Append("  DoubleFormatBasePrice: ").Append(DoubleFormatBasePrice).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  HasTierPrices: ").Append(HasTierPrices).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
