/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using pricelist.Client;
using pricelist.Api;
// uncomment below to import models
//using pricelist.Model;

namespace pricelist.Test.Api
{
    /// <summary>
    ///  Class for testing PriceListApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PriceListApiTests : IDisposable
    {
        private PriceListApi instance;

        public PriceListApiTests()
        {
            instance = new PriceListApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriceListApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PriceListApi
            //Assert.IsType<PriceListApi>(instance);
        }

        /// <summary>
        /// Test PriceListCreatePriceList
        /// </summary>
        [Fact]
        public void PriceListCreatePriceListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistCreatePriceListRequest body = null;
            //var response = instance.PriceListCreatePriceList(body);
            //Assert.IsType<PricelistCreatePriceListResponse>(response);
        }

        /// <summary>
        /// Test PriceListDeletePriceListItems
        /// </summary>
        [Fact]
        public void PriceListDeletePriceListItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistDeletePriceListItemsRequest body = null;
            //var response = instance.PriceListDeletePriceListItems(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test PriceListGetFullPriceItemsByPricelistId
        /// </summary>
        [Fact]
        public void PriceListGetFullPriceItemsByPricelistIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetFullPriceItemsRequest body = null;
            //var response = instance.PriceListGetFullPriceItemsByPricelistId(body);
            //Assert.IsType<PricelistGetFullPriceItemsResponse>(response);
        }

        /// <summary>
        /// Test PriceListGetPriceItemsByPriceListItemIds
        /// </summary>
        [Fact]
        public void PriceListGetPriceItemsByPriceListItemIdsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPriceItemsByPriceListItemIdsRequest body = null;
            //var response = instance.PriceListGetPriceItemsByPriceListItemIds(body);
            //Assert.IsType<PricelistGetPriceItemsByPriceListItemIdsResponse>(response);
        }

        /// <summary>
        /// Test PriceListGetPriceList
        /// </summary>
        [Fact]
        public void PriceListGetPriceListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPriceListRequest body = null;
            //var response = instance.PriceListGetPriceList(body);
            //Assert.IsType<PricelistGetPriceListResponse>(response);
        }

        /// <summary>
        /// Test PriceListGetPriceListByCode
        /// </summary>
        [Fact]
        public void PriceListGetPriceListByCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPriceListByCodeRequest body = null;
            //var response = instance.PriceListGetPriceListByCode(body);
            //Assert.IsType<PricelistGetPriceListByCodeResponse>(response);
        }

        /// <summary>
        /// Test PriceListGetPriceListItems
        /// </summary>
        [Fact]
        public void PriceListGetPriceListItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPriceListItemsRequest body = null;
            //var response = instance.PriceListGetPriceListItems(body);
            //Assert.IsType<PricelistGetPriceListItemsResponse>(response);
        }

        /// <summary>
        /// Test PriceListGetPricesItems
        /// </summary>
        [Fact]
        public void PriceListGetPricesItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPricesRequest body = null;
            //var response = instance.PriceListGetPricesItems(body);
            //Assert.IsType<PricelistGetPricesResponse>(response);
        }

        /// <summary>
        /// Test PriceListListFullPriceItemsByPricelistId
        /// </summary>
        [Fact]
        public void PriceListListFullPriceItemsByPricelistIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistListFullPriceItemsRequest body = null;
            //var response = instance.PriceListListFullPriceItemsByPricelistId(body);
            //Assert.IsType<PricelistListFullPriceItemsResponse>(response);
        }

        /// <summary>
        /// Test PriceListListPriceLists
        /// </summary>
        [Fact]
        public void PriceListListPriceListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistListPriceListsRequest body = null;
            //var response = instance.PriceListListPriceLists(body);
            //Assert.IsType<PricelistListPriceListsResponse>(response);
        }

        /// <summary>
        /// Test PriceListSetPriceListItems
        /// </summary>
        [Fact]
        public void PriceListSetPriceListItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistSetPriceListItemsRequest body = null;
            //var response = instance.PriceListSetPriceListItems(body);
            //Assert.IsType<PricelistSetPriceListItemsResponse>(response);
        }

        /// <summary>
        /// Test PriceListUpdatePriceList
        /// </summary>
        [Fact]
        public void PriceListUpdatePriceListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistUpdatePriceListRequest body = null;
            //var response = instance.PriceListUpdatePriceList(body);
            //Assert.IsType<Object>(response);
        }
    }
}
