/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using pricelist.Client;
using pricelist.Api;
// uncomment below to import models
//using pricelist.Model;

namespace pricelist.Test.Api
{
    /// <summary>
    ///  Class for testing PriceListApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PriceListApiTests : IDisposable
    {
        private PriceListApi instance;

        public PriceListApiTests()
        {
            instance = new PriceListApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriceListApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PriceListApi
            //Assert.IsType<PriceListApi>(instance);
        }

        /// <summary>
        /// Test CreatePriceList
        /// </summary>
        [Fact]
        public void CreatePriceListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistCreatePriceListRequest body = null;
            //var response = instance.CreatePriceList(body);
            //Assert.IsType<PricelistCreatePriceListResponse>(response);
        }

        /// <summary>
        /// Test DeletePriceListItems
        /// </summary>
        [Fact]
        public void DeletePriceListItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistDeletePriceListItemsRequest body = null;
            //var response = instance.DeletePriceListItems(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test GetFullPriceItemsByPricelistId
        /// </summary>
        [Fact]
        public void GetFullPriceItemsByPricelistIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetFullPriceItemsRequest body = null;
            //var response = instance.GetFullPriceItemsByPricelistId(body);
            //Assert.IsType<PricelistGetFullPriceItemsResponse>(response);
        }

        /// <summary>
        /// Test GetPriceList
        /// </summary>
        [Fact]
        public void GetPriceListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPriceListRequest body = null;
            //var response = instance.GetPriceList(body);
            //Assert.IsType<PricelistGetPriceListResponse>(response);
        }

        /// <summary>
        /// Test GetPriceListByCode
        /// </summary>
        [Fact]
        public void GetPriceListByCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPriceListByCodeRequest body = null;
            //var response = instance.GetPriceListByCode(body);
            //Assert.IsType<PricelistGetPriceListByCodeResponse>(response);
        }

        /// <summary>
        /// Test GetPriceListItems
        /// </summary>
        [Fact]
        public void GetPriceListItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPriceListItemsRequest body = null;
            //var response = instance.GetPriceListItems(body);
            //Assert.IsType<PricelistGetPriceListItemsResponse>(response);
        }

        /// <summary>
        /// Test GetPricesItems
        /// </summary>
        [Fact]
        public void GetPricesItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPricesRequest body = null;
            //var response = instance.GetPricesItems(body);
            //Assert.IsType<PricelistGetPricesResponse>(response);
        }

        /// <summary>
        /// Test ListFullPriceItemsByPricelistId
        /// </summary>
        [Fact]
        public void ListFullPriceItemsByPricelistIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistListFullPriceItemsRequest body = null;
            //var response = instance.ListFullPriceItemsByPricelistId(body);
            //Assert.IsType<PricelistListFullPriceItemsResponse>(response);
        }

        /// <summary>
        /// Test ListPriceLists
        /// </summary>
        [Fact]
        public void ListPriceListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistListPriceListsRequest body = null;
            //var response = instance.ListPriceLists(body);
            //Assert.IsType<PricelistListPriceListsResponse>(response);
        }

        /// <summary>
        /// Test PriceListGetPriceItemsByPriceListItemIds
        /// </summary>
        [Fact]
        public void PriceListGetPriceItemsByPriceListItemIdsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistGetPriceItemsByPriceListItemIdsRequest body = null;
            //var response = instance.PriceListGetPriceItemsByPriceListItemIds(body);
            //Assert.IsType<PricelistGetPriceItemsByPriceListItemIdsResponse>(response);
        }

        /// <summary>
        /// Test SetPriceListItems
        /// </summary>
        [Fact]
        public void SetPriceListItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistSetPriceListItemsRequest body = null;
            //var response = instance.SetPriceListItems(body);
            //Assert.IsType<PricelistSetPriceListItemsResponse>(response);
        }

        /// <summary>
        /// Test UpdatePriceList
        /// </summary>
        [Fact]
        public void UpdatePriceListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PricelistUpdatePriceListRequest body = null;
            //var response = instance.UpdatePriceList(body);
            //Assert.IsType<Object>(response);
        }
    }
}
