/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing ListPriceListsRequestFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListPriceListsRequestFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListPriceListsRequestFilter
        //private ListPriceListsRequestFilter instance;

        public ListPriceListsRequestFilterTests()
        {
            // TODO uncomment below to create an instance of ListPriceListsRequestFilter
            //instance = new ListPriceListsRequestFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListPriceListsRequestFilter
        /// </summary>
        [Fact]
        public void ListPriceListsRequestFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListPriceListsRequestFilter
            //Assert.IsType<ListPriceListsRequestFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'CurrencyFilter'
        /// </summary>
        [Fact]
        public void CurrencyFilterTest()
        {
            // TODO unit test for the property 'CurrencyFilter'
        }

        /// <summary>
        /// Test the property 'VatIncluded'
        /// </summary>
        [Fact]
        public void VatIncludedTest()
        {
            // TODO unit test for the property 'VatIncluded'
        }

        /// <summary>
        /// Test the property 'DeliveredDutyPaid'
        /// </summary>
        [Fact]
        public void DeliveredDutyPaidTest()
        {
            // TODO unit test for the property 'DeliveredDutyPaid'
        }

        /// <summary>
        /// Test the property 'SegmentsFilter'
        /// </summary>
        [Fact]
        public void SegmentsFilterTest()
        {
            // TODO unit test for the property 'SegmentsFilter'
        }

        /// <summary>
        /// Test the property 'MarketsFilter'
        /// </summary>
        [Fact]
        public void MarketsFilterTest()
        {
            // TODO unit test for the property 'MarketsFilter'
        }

        /// <summary>
        /// Test the property 'ChannelsFilter'
        /// </summary>
        [Fact]
        public void ChannelsFilterTest()
        {
            // TODO unit test for the property 'ChannelsFilter'
        }

        /// <summary>
        /// Test the property 'TypeFilter'
        /// </summary>
        [Fact]
        public void TypeFilterTest()
        {
            // TODO unit test for the property 'TypeFilter'
        }

        /// <summary>
        /// Test the property 'IsSystem'
        /// </summary>
        [Fact]
        public void IsSystemTest()
        {
            // TODO unit test for the property 'IsSystem'
        }
    }
}
