/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistMarketFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistMarketFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistMarketFilter
        //private PricelistMarketFilter instance;

        public PricelistMarketFilterTests()
        {
            // TODO uncomment below to create an instance of PricelistMarketFilter
            //instance = new PricelistMarketFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistMarketFilter
        /// </summary>
        [Fact]
        public void PricelistMarketFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistMarketFilter
            //Assert.IsType<PricelistMarketFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Markets'
        /// </summary>
        [Fact]
        public void MarketsTest()
        {
            // TODO unit test for the property 'Markets'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
    }
}
