/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistSetPriceListItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistSetPriceListItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistSetPriceListItem
        //private PricelistSetPriceListItem instance;

        public PricelistSetPriceListItemTests()
        {
            // TODO uncomment below to create an instance of PricelistSetPriceListItem
            //instance = new PricelistSetPriceListItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistSetPriceListItem
        /// </summary>
        [Fact]
        public void PricelistSetPriceListItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistSetPriceListItem
            //Assert.IsType<PricelistSetPriceListItem>(instance);
        }

        /// <summary>
        /// Test the property 'ItemGrn'
        /// </summary>
        [Fact]
        public void ItemGrnTest()
        {
            // TODO unit test for the property 'ItemGrn'
        }

        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Fact]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }

        /// <summary>
        /// Test the property 'PriceItems'
        /// </summary>
        [Fact]
        public void PriceItemsTest()
        {
            // TODO unit test for the property 'PriceItems'
        }

        /// <summary>
        /// Test the property 'HasTierPrices'
        /// </summary>
        [Fact]
        public void HasTierPricesTest()
        {
            // TODO unit test for the property 'HasTierPrices'
        }
    }
}
