/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetFullPriceItemsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetFullPriceItemsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetFullPriceItemsResponse
        //private PricelistGetFullPriceItemsResponse instance;

        public PricelistGetFullPriceItemsResponseTests()
        {
            // TODO uncomment below to create an instance of PricelistGetFullPriceItemsResponse
            //instance = new PricelistGetFullPriceItemsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetFullPriceItemsResponse
        /// </summary>
        [Fact]
        public void PricelistGetFullPriceItemsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetFullPriceItemsResponse
            //Assert.IsType<PricelistGetFullPriceItemsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PriceItems'
        /// </summary>
        [Fact]
        public void PriceItemsTest()
        {
            // TODO unit test for the property 'PriceItems'
        }
    }
}
