/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistPriceListTypeFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistPriceListTypeFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistPriceListTypeFilter
        //private PricelistPriceListTypeFilter instance;

        public PricelistPriceListTypeFilterTests()
        {
            // TODO uncomment below to create an instance of PricelistPriceListTypeFilter
            //instance = new PricelistPriceListTypeFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistPriceListTypeFilter
        /// </summary>
        [Fact]
        public void PricelistPriceListTypeFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistPriceListTypeFilter
            //Assert.IsType<PricelistPriceListTypeFilter>(instance);
        }

        /// <summary>
        /// Test the property 'PricelistTypes'
        /// </summary>
        [Fact]
        public void PricelistTypesTest()
        {
            // TODO unit test for the property 'PricelistTypes'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
    }
}
