/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetFullPriceItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetFullPriceItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetFullPriceItem
        //private PricelistGetFullPriceItem instance;

        public PricelistGetFullPriceItemTests()
        {
            // TODO uncomment below to create an instance of PricelistGetFullPriceItem
            //instance = new PricelistGetFullPriceItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetFullPriceItem
        /// </summary>
        [Fact]
        public void PricelistGetFullPriceItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetFullPriceItem
            //Assert.IsType<PricelistGetFullPriceItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'ItemGrn'
        /// </summary>
        [Fact]
        public void ItemGrnTest()
        {
            // TODO unit test for the property 'ItemGrn'
        }

        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Fact]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Prices'
        /// </summary>
        [Fact]
        public void PricesTest()
        {
            // TODO unit test for the property 'Prices'
        }

        /// <summary>
        /// Test the property 'HasTierPrices'
        /// </summary>
        [Fact]
        public void HasTierPricesTest()
        {
            // TODO unit test for the property 'HasTierPrices'
        }
    }
}
