/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistMoney
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistMoneyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistMoney
        //private PricelistMoney instance;

        public PricelistMoneyTests()
        {
            // TODO uncomment below to create an instance of PricelistMoney
            //instance = new PricelistMoney();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistMoney
        /// </summary>
        [Fact]
        public void PricelistMoneyInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistMoney
            //Assert.IsType<PricelistMoney>(instance);
        }

        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

        /// <summary>
        /// Test the property 'Micros'
        /// </summary>
        [Fact]
        public void MicrosTest()
        {
            // TODO unit test for the property 'Micros'
        }
    }
}
