/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistSetPriceListItemsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistSetPriceListItemsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistSetPriceListItemsResponse
        //private PricelistSetPriceListItemsResponse instance;

        public PricelistSetPriceListItemsResponseTests()
        {
            // TODO uncomment below to create an instance of PricelistSetPriceListItemsResponse
            //instance = new PricelistSetPriceListItemsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistSetPriceListItemsResponse
        /// </summary>
        [Fact]
        public void PricelistSetPriceListItemsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistSetPriceListItemsResponse
            //Assert.IsType<PricelistSetPriceListItemsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
