/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetPriceListItemsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetPriceListItemsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetPriceListItemsResponse
        //private PricelistGetPriceListItemsResponse instance;

        public PricelistGetPriceListItemsResponseTests()
        {
            // TODO uncomment below to create an instance of PricelistGetPriceListItemsResponse
            //instance = new PricelistGetPriceListItemsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetPriceListItemsResponse
        /// </summary>
        [Fact]
        public void PricelistGetPriceListItemsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetPriceListItemsResponse
            //Assert.IsType<PricelistGetPriceListItemsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
