/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistListFullPriceItemsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistListFullPriceItemsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistListFullPriceItemsResponse
        //private PricelistListFullPriceItemsResponse instance;

        public PricelistListFullPriceItemsResponseTests()
        {
            // TODO uncomment below to create an instance of PricelistListFullPriceItemsResponse
            //instance = new PricelistListFullPriceItemsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistListFullPriceItemsResponse
        /// </summary>
        [Fact]
        public void PricelistListFullPriceItemsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistListFullPriceItemsResponse
            //Assert.IsType<PricelistListFullPriceItemsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
