/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistCreatePriceListRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistCreatePriceListRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistCreatePriceListRequest
        //private PricelistCreatePriceListRequest instance;

        public PricelistCreatePriceListRequestTests()
        {
            // TODO uncomment below to create an instance of PricelistCreatePriceListRequest
            //instance = new PricelistCreatePriceListRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistCreatePriceListRequest
        /// </summary>
        [Fact]
        public void PricelistCreatePriceListRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistCreatePriceListRequest
            //Assert.IsType<PricelistCreatePriceListRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'VatIncluded'
        /// </summary>
        [Fact]
        public void VatIncludedTest()
        {
            // TODO unit test for the property 'VatIncluded'
        }

        /// <summary>
        /// Test the property 'DeliveredDutyPaid'
        /// </summary>
        [Fact]
        public void DeliveredDutyPaidTest()
        {
            // TODO unit test for the property 'DeliveredDutyPaid'
        }

        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Fact]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }

        /// <summary>
        /// Test the property 'Markets'
        /// </summary>
        [Fact]
        public void MarketsTest()
        {
            // TODO unit test for the property 'Markets'
        }

        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'IsSystem'
        /// </summary>
        [Fact]
        public void IsSystemTest()
        {
            // TODO unit test for the property 'IsSystem'
        }
    }
}
