/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistListPriceListsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistListPriceListsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistListPriceListsRequest
        //private PricelistListPriceListsRequest instance;

        public PricelistListPriceListsRequestTests()
        {
            // TODO uncomment below to create an instance of PricelistListPriceListsRequest
            //instance = new PricelistListPriceListsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistListPriceListsRequest
        /// </summary>
        [Fact]
        public void PricelistListPriceListsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistListPriceListsRequest
            //Assert.IsType<PricelistListPriceListsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'PageToken'
        /// </summary>
        [Fact]
        public void PageTokenTest()
        {
            // TODO unit test for the property 'PageToken'
        }

        /// <summary>
        /// Test the property 'SearchQuery'
        /// </summary>
        [Fact]
        public void SearchQueryTest()
        {
            // TODO unit test for the property 'SearchQuery'
        }

        /// <summary>
        /// Test the property 'FilterMask'
        /// </summary>
        [Fact]
        public void FilterMaskTest()
        {
            // TODO unit test for the property 'FilterMask'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
    }
}
