/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetPricesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetPricesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetPricesRequest
        //private PricelistGetPricesRequest instance;

        public PricelistGetPricesRequestTests()
        {
            // TODO uncomment below to create an instance of PricelistGetPricesRequest
            //instance = new PricelistGetPricesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetPricesRequest
        /// </summary>
        [Fact]
        public void PricelistGetPricesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetPricesRequest
            //Assert.IsType<PricelistGetPricesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ItemsGrn'
        /// </summary>
        [Fact]
        public void ItemsGrnTest()
        {
            // TODO unit test for the property 'ItemsGrn'
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
    }
}
