/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistPriceContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistPriceContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistPriceContext
        //private PricelistPriceContext instance;

        public PricelistPriceContextTests()
        {
            // TODO uncomment below to create an instance of PricelistPriceContext
            //instance = new PricelistPriceContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistPriceContext
        /// </summary>
        [Fact]
        public void PricelistPriceContextInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistPriceContext
            //Assert.IsType<PricelistPriceContext>(instance);
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Segment'
        /// </summary>
        [Fact]
        public void SegmentTest()
        {
            // TODO unit test for the property 'Segment'
        }

        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Fact]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }

        /// <summary>
        /// Test the property 'Market'
        /// </summary>
        [Fact]
        public void MarketTest()
        {
            // TODO unit test for the property 'Market'
        }

        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
    }
}
