/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistListPriceListsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistListPriceListsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistListPriceListsResponse
        //private PricelistListPriceListsResponse instance;

        public PricelistListPriceListsResponseTests()
        {
            // TODO uncomment below to create an instance of PricelistListPriceListsResponse
            //instance = new PricelistListPriceListsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistListPriceListsResponse
        /// </summary>
        [Fact]
        public void PricelistListPriceListsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistListPriceListsResponse
            //Assert.IsType<PricelistListPriceListsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Pricelists'
        /// </summary>
        [Fact]
        public void PricelistsTest()
        {
            // TODO unit test for the property 'Pricelists'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
