/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetFullPriceItemPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetFullPriceItemPriceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetFullPriceItemPrice
        //private PricelistGetFullPriceItemPrice instance;

        public PricelistGetFullPriceItemPriceTests()
        {
            // TODO uncomment below to create an instance of PricelistGetFullPriceItemPrice
            //instance = new PricelistGetFullPriceItemPrice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetFullPriceItemPrice
        /// </summary>
        [Fact]
        public void PricelistGetFullPriceItemPriceInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetFullPriceItemPrice
            //Assert.IsType<PricelistGetFullPriceItemPrice>(instance);
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Fact]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }

        /// <summary>
        /// Test the property 'StartAt'
        /// </summary>
        [Fact]
        public void StartAtTest()
        {
            // TODO unit test for the property 'StartAt'
        }

        /// <summary>
        /// Test the property 'EndAt'
        /// </summary>
        [Fact]
        public void EndAtTest()
        {
            // TODO unit test for the property 'EndAt'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Fact]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }
    }
}
