/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistUpdatePriceListRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistUpdatePriceListRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistUpdatePriceListRequestPayload
        //private PricelistUpdatePriceListRequestPayload instance;

        public PricelistUpdatePriceListRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of PricelistUpdatePriceListRequestPayload
            //instance = new PricelistUpdatePriceListRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistUpdatePriceListRequestPayload
        /// </summary>
        [Fact]
        public void PricelistUpdatePriceListRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistUpdatePriceListRequestPayload
            //Assert.IsType<PricelistUpdatePriceListRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'VatIncluded'
        /// </summary>
        [Fact]
        public void VatIncludedTest()
        {
            // TODO unit test for the property 'VatIncluded'
        }

        /// <summary>
        /// Test the property 'DeliveredDutyPaid'
        /// </summary>
        [Fact]
        public void DeliveredDutyPaidTest()
        {
            // TODO unit test for the property 'DeliveredDutyPaid'
        }

        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Fact]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }

        /// <summary>
        /// Test the property 'Markets'
        /// </summary>
        [Fact]
        public void MarketsTest()
        {
            // TODO unit test for the property 'Markets'
        }

        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'IsSystem'
        /// </summary>
        [Fact]
        public void IsSystemTest()
        {
            // TODO unit test for the property 'IsSystem'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
