/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetFullPriceItemsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetFullPriceItemsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetFullPriceItemsRequest
        //private PricelistGetFullPriceItemsRequest instance;

        public PricelistGetFullPriceItemsRequestTests()
        {
            // TODO uncomment below to create an instance of PricelistGetFullPriceItemsRequest
            //instance = new PricelistGetFullPriceItemsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetFullPriceItemsRequest
        /// </summary>
        [Fact]
        public void PricelistGetFullPriceItemsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetFullPriceItemsRequest
            //Assert.IsType<PricelistGetFullPriceItemsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'PricelistId'
        /// </summary>
        [Fact]
        public void PricelistIdTest()
        {
            // TODO unit test for the property 'PricelistId'
        }

        /// <summary>
        /// Test the property 'ItemsGrn'
        /// </summary>
        [Fact]
        public void ItemsGrnTest()
        {
            // TODO unit test for the property 'ItemsGrn'
        }
    }
}
