/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetPriceListItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetPriceListItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetPriceListItem
        //private PricelistGetPriceListItem instance;

        public PricelistGetPriceListItemTests()
        {
            // TODO uncomment below to create an instance of PricelistGetPriceListItem
            //instance = new PricelistGetPriceListItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetPriceListItem
        /// </summary>
        [Fact]
        public void PricelistGetPriceListItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetPriceListItem
            //Assert.IsType<PricelistGetPriceListItem>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'ItemGrn'
        /// </summary>
        [Fact]
        public void ItemGrnTest()
        {
            // TODO unit test for the property 'ItemGrn'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'DoubleFormatPrice'
        /// </summary>
        [Fact]
        public void DoubleFormatPriceTest()
        {
            // TODO unit test for the property 'DoubleFormatPrice'
        }

        /// <summary>
        /// Test the property 'EndDatePrice'
        /// </summary>
        [Fact]
        public void EndDatePriceTest()
        {
            // TODO unit test for the property 'EndDatePrice'
        }

        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Fact]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }

        /// <summary>
        /// Test the property 'DoubleFormatBasePrice'
        /// </summary>
        [Fact]
        public void DoubleFormatBasePriceTest()
        {
            // TODO unit test for the property 'DoubleFormatBasePrice'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'HasTierPrices'
        /// </summary>
        [Fact]
        public void HasTierPricesTest()
        {
            // TODO unit test for the property 'HasTierPrices'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
