/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistFilterCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistFilterConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistFilterCondition
        //private PricelistFilterCondition instance;

        public PricelistFilterConditionTests()
        {
            // TODO uncomment below to create an instance of PricelistFilterCondition
            //instance = new PricelistFilterCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistFilterCondition
        /// </summary>
        [Fact]
        public void PricelistFilterConditionInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistFilterCondition
            //Assert.IsType<PricelistFilterCondition>(instance);
        }
    }
}
