/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistCurrencyFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistCurrencyFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistCurrencyFilter
        //private PricelistCurrencyFilter instance;

        public PricelistCurrencyFilterTests()
        {
            // TODO uncomment below to create an instance of PricelistCurrencyFilter
            //instance = new PricelistCurrencyFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistCurrencyFilter
        /// </summary>
        [Fact]
        public void PricelistCurrencyFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistCurrencyFilter
            //Assert.IsType<PricelistCurrencyFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Currencies'
        /// </summary>
        [Fact]
        public void CurrenciesTest()
        {
            // TODO unit test for the property 'Currencies'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
    }
}
