/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetPriceItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetPriceItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetPriceItem
        //private PricelistGetPriceItem instance;

        public PricelistGetPriceItemTests()
        {
            // TODO uncomment below to create an instance of PricelistGetPriceItem
            //instance = new PricelistGetPriceItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetPriceItem
        /// </summary>
        [Fact]
        public void PricelistGetPriceItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetPriceItem
            //Assert.IsType<PricelistGetPriceItem>(instance);
        }

        /// <summary>
        /// Test the property 'ItemGrn'
        /// </summary>
        [Fact]
        public void ItemGrnTest()
        {
            // TODO unit test for the property 'ItemGrn'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'DoubleFormatPrice'
        /// </summary>
        [Fact]
        public void DoubleFormatPriceTest()
        {
            // TODO unit test for the property 'DoubleFormatPrice'
        }

        /// <summary>
        /// Test the property 'EndDatePrice'
        /// </summary>
        [Fact]
        public void EndDatePriceTest()
        {
            // TODO unit test for the property 'EndDatePrice'
        }

        /// <summary>
        /// Test the property 'BasePrice'
        /// </summary>
        [Fact]
        public void BasePriceTest()
        {
            // TODO unit test for the property 'BasePrice'
        }

        /// <summary>
        /// Test the property 'DoubleFormatBasePrice'
        /// </summary>
        [Fact]
        public void DoubleFormatBasePriceTest()
        {
            // TODO unit test for the property 'DoubleFormatBasePrice'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'HasTierPrices'
        /// </summary>
        [Fact]
        public void HasTierPricesTest()
        {
            // TODO unit test for the property 'HasTierPrices'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
