/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetPriceItemsByPriceListItemIdsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetPriceItemsByPriceListItemIdsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetPriceItemsByPriceListItemIdsResponse
        //private PricelistGetPriceItemsByPriceListItemIdsResponse instance;

        public PricelistGetPriceItemsByPriceListItemIdsResponseTests()
        {
            // TODO uncomment below to create an instance of PricelistGetPriceItemsByPriceListItemIdsResponse
            //instance = new PricelistGetPriceItemsByPriceListItemIdsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetPriceItemsByPriceListItemIdsResponse
        /// </summary>
        [Fact]
        public void PricelistGetPriceItemsByPriceListItemIdsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetPriceItemsByPriceListItemIdsResponse
            //Assert.IsType<PricelistGetPriceItemsByPriceListItemIdsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Prices'
        /// </summary>
        [Fact]
        public void PricesTest()
        {
            // TODO unit test for the property 'Prices'
        }
    }
}
