/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistSetPriceListItemsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistSetPriceListItemsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistSetPriceListItemsRequest
        //private PricelistSetPriceListItemsRequest instance;

        public PricelistSetPriceListItemsRequestTests()
        {
            // TODO uncomment below to create an instance of PricelistSetPriceListItemsRequest
            //instance = new PricelistSetPriceListItemsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistSetPriceListItemsRequest
        /// </summary>
        [Fact]
        public void PricelistSetPriceListItemsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistSetPriceListItemsRequest
            //Assert.IsType<PricelistSetPriceListItemsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
