/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistChannelFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistChannelFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistChannelFilter
        //private PricelistChannelFilter instance;

        public PricelistChannelFilterTests()
        {
            // TODO uncomment below to create an instance of PricelistChannelFilter
            //instance = new PricelistChannelFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistChannelFilter
        /// </summary>
        [Fact]
        public void PricelistChannelFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistChannelFilter
            //Assert.IsType<PricelistChannelFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
    }
}
