/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistCreatePriceListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistCreatePriceListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistCreatePriceListResponse
        //private PricelistCreatePriceListResponse instance;

        public PricelistCreatePriceListResponseTests()
        {
            // TODO uncomment below to create an instance of PricelistCreatePriceListResponse
            //instance = new PricelistCreatePriceListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistCreatePriceListResponse
        /// </summary>
        [Fact]
        public void PricelistCreatePriceListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistCreatePriceListResponse
            //Assert.IsType<PricelistCreatePriceListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }
    }
}
