/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistGetPriceListByCodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistGetPriceListByCodeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistGetPriceListByCodeRequest
        //private PricelistGetPriceListByCodeRequest instance;

        public PricelistGetPriceListByCodeRequestTests()
        {
            // TODO uncomment below to create an instance of PricelistGetPriceListByCodeRequest
            //instance = new PricelistGetPriceListByCodeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistGetPriceListByCodeRequest
        /// </summary>
        [Fact]
        public void PricelistGetPriceListByCodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistGetPriceListByCodeRequest
            //Assert.IsType<PricelistGetPriceListByCodeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
