/*
 * PriceList Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistSetPriceListItemError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistSetPriceListItemErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistSetPriceListItemError
        //private PricelistSetPriceListItemError instance;

        public PricelistSetPriceListItemErrorTests()
        {
            // TODO uncomment below to create an instance of PricelistSetPriceListItemError
            //instance = new PricelistSetPriceListItemError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistSetPriceListItemError
        /// </summary>
        [Fact]
        public void PricelistSetPriceListItemErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistSetPriceListItemError
            //Assert.IsType<PricelistSetPriceListItemError>(instance);
        }

        /// <summary>
        /// Test the property 'ItemGrn'
        /// </summary>
        [Fact]
        public void ItemGrnTest()
        {
            // TODO unit test for the property 'ItemGrn'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
