/*
 * pricelist/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using pricelist.Model;
using pricelist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace pricelist.Test.Model
{
    /// <summary>
    ///  Class for testing PricelistCurrency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricelistCurrencyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricelistCurrency
        //private PricelistCurrency instance;

        public PricelistCurrencyTests()
        {
            // TODO uncomment below to create an instance of PricelistCurrency
            //instance = new PricelistCurrency();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricelistCurrency
        /// </summary>
        [Fact]
        public void PricelistCurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricelistCurrency
            //Assert.IsType<PricelistCurrency>(instance);
        }
    }
}
